#!/usr/bin/python3

"""
Module that factorizes numbers into 
two smaller numbers
"""

from sys import argv


def factor(n):
  i = 2
  if n < 2:
    return

  while n % i:
    j = n // i
    i += 1
  print("{} = {} * {}".format(n, i, j))



if len(argv) != 2:
  print("Usage: factors <file>")
  exit()

try:
  with open(argv[1], "r") as file:
    line = file.readline()

    while line != "":
      n = int(line.split('\n')[0])
      factor(n)
      line = file.readline()
      
except:
  pass
  
 
      
